# Generated by Django 5.1.3 on 2024-11-21 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('allocation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('asset_barcode', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=255)),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('assign_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.CharField(default=345, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_role', to='app.role'),
        ),
    ]
