# Generated by Django 5.1.3 on 2024-12-12 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='asset_type',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='stationdetails',
            old_name='staion_code',
            new_name='station_address',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_status',
            field=models.CharField(choices=[('in-use', 'In Use'), ('available', 'Available'), ('expired', 'Expired'), ('in-maintenance', 'In Maintenance')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='stationdetails',
            name='station_code',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('below-average', 'Below Average')], default='good', max_length=20),
        ),
        migrations.CreateModel(
            name='AssetSubCategory',
            fields=[
                ('sub_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.assetcategory')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.assetsubcategory'),
        ),
        migrations.CreateModel(
            name='ExpiredProduct',
            fields=[
                ('expired_id', models.AutoField(primary_key=True, serialize=False)),
                ('expiration_date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(default='Expired status set by admin', max_length=255)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expired_record', to='app.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('last_maintenance_date', models.DateField(blank=True, null=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('maintenance_cost', models.CharField(blank=True, max_length=255, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.asset')),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.role')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.stationdetails')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAsset',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.CharField(max_length=255)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_location', models.CharField(max_length=255)),
                ('request_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.asset')),
                ('asset_sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.assetsubcategory')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.userdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('allocation_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('assign_date', models.DateField(auto_now_add=True)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('assign_location', models.CharField(max_length=255)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.asset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.userdetails')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='assign_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.userdetails'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
