# Generated by Django 5.1.3 on 2024-11-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_role_remove_user_status_asset_assign_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='user',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='asset',
            name='assign_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
