# Generated by Django 5.1.3 on 2024-11-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_status_user_is_active_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='assign_to',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
