# Generated by Django 5.1.3 on 2024-11-19 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
