# Generated by Django 5.1.3 on 2024-12-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_assetsubcategory_sub_category_image_returnedproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_add_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
