# Generated by Django 5.1.3 on 2024-12-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_asset_asset_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allocation',
            name='assign_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
