# Generated by Django 5.1.3 on 2024-11-25 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_role_alter_user_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.CreateModel(
            name='AssetSubCategory',
            fields=[
                ('sub_category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.assetcategory')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='AssetCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.assetsubcategory'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('maintenance_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('last_maintenance_date', models.DateField()),
                ('next_maintenance_date', models.DateField()),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.asset')),
            ],
        ),
        migrations.CreateModel(
            name='RequestAsset',
            fields=[
                ('request_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('quantity', models.CharField(max_length=255)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_location', models.CharField(max_length=255)),
                ('status', models.CharField(default='Pending', max_length=255)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.asset')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.user')),
            ],
        ),
    ]
