# Generated by Django 5.0.6 on 2024-12-12 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_returnedproducts_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returnedproducts',
            old_name='allocation_id',
            new_name='allocation',
        ),
    ]
