# Generated by Django 5.0.6 on 2024-12-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_allocation_id_returnedproducts_allocation'),
        ('app', '0006_tender'),
    ]

    operations = [
    ]
