# Generated by Django 5.0.6 on 2024-11-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_assetcategory_asset_asset_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
