# Generated by Django 5.1.3 on 2024-11-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_assetcategory_asset_asset_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stationdetails',
            old_name='staion_code',
            new_name='station_code',
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
