# Generated by Django 5.0.6 on 2024-11-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_staion_code_stationdetails_station_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_image',
        ),
    ]
