# Generated by Django 5.1.3 on 2024-12-07 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_user_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('condition_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('condition', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='asset_barcode',
        ),
        migrations.RemoveField(
            model_name='requestasset',
            name='status',
        ),
        migrations.AddField(
            model_name='allocation',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.asset'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_status',
            field=models.CharField(choices=[('in-use', 'In Use'), ('available', 'Available'), ('expired', 'Expired'), ('in-maintenance', 'In Maintenance')], default='available', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_cost',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maintenance',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestasset',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='requestasset',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stationdetails',
            name='station_address',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.condition'),
        ),
    ]
