# Generated by Django 5.0.6 on 2024-12-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_maintenance_cost'),
        ('app', '0010_remove_user_user_image'),
    ]

    operations = [
    ]
