# Generated by Django 5.1.3 on 2024-12-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_condition_status_rename_full_name_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('good', 'Good'), ('expired', 'Expired')], default='good', max_length=20),
        ),
        migrations.DeleteModel(
            name='Condition',
        ),
    ]
