# Generated by Django 5.1.3 on 2024-12-07 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_asset_condition_delete_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('good', 'Good'), ('average', 'Average'), ('below-average', 'Below Average')], default='good', max_length=20),
        ),
        migrations.CreateModel(
            name='ExpiredProduct',
            fields=[
                ('expired_id', models.AutoField(primary_key=True, serialize=False)),
                ('expiration_date', models.DateField(auto_now_add=True)),
                ('reason', models.CharField(default='Expired status set by admin', max_length=255)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expired_record', to='app.asset')),
            ],
        ),
    ]
