# Generated by Django 5.0.6 on 2024-12-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_maintenance_cost'),
        ('app', '0013_alter_asset_condition_expiredproduct'),
    ]

    operations = [
    ]
