# Generated by Django 5.0.6 on 2024-12-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_merge_20241207_1500'),
        ('app', '0013_alter_asset_condition_expiredproduct'),
    ]

    operations = [
    ]
