# Generated by Django 5.0.6 on 2024-12-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20241208_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='cost',
        ),
    ]
