# Generated by Django 5.1.3 on 2024-12-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_maintenance_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='barcode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
