# Generated by Django 5.0.6 on 2024-12-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_maintenance_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserDetails',
        ),
    ]
