# Generated by Django 5.1.3 on 2024-12-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_maintenance_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
