# Generated by Django 5.0.6 on 2024-12-11 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_user_userdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.asset'),
        ),
    ]
