# Generated by Django 5.1.3 on 2024-12-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_asset_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_cost',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
