# Generated by Django 5.1.3 on 2024-12-09 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_merge_20241208_1548'),
        ('app', '0014_merge_20241208_1644'),
        ('app', '0017_alter_maintenance_maintenance_cost'),
    ]

    operations = [
    ]
