# Generated by Django 5.1.3 on 2024-12-09 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_merge_20241209_1533'),
        ('app', '0018_merge_20241210_0229'),
    ]

    operations = [
    ]
