# Generated by Django 5.1.3 on 2024-12-10 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_merge_20241210_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestasset',
            name='asset',
        ),
        migrations.AddField(
            model_name='requestasset',
            name='asset_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.assetsubcategory'),
        ),
    ]
