# Generated by Django 5.1.3 on 2024-12-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_requestasset_asset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
