# Generated by Django 5.1.3 on 2024-12-11 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_asset_asset_maintenance_date'),
        ('app', '0017_alter_maintenance_asset'),
        ('app', '0021_alter_maintenance_last_maintenance_date_and_more'),
    ]

    operations = [
    ]
